# Generated by Django 4.1.7 on 2023-04-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('email', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('subject', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('message', models.TextField()),
            ],
        ),
    ]
