# Generated by Django 4.1.7 on 2023-07-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio_page_view_count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_view_count', models.IntegerField(default=0)),
                ('about_view_count', models.IntegerField(default=0)),
                ('contact_view_count', models.IntegerField(default=0)),
            ],
        ),
    ]
