# Generated by Django 4.1.7 on 2025-01-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_portfolio_page_view_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('browser_name', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('browser_version', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('server_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('server_port', models.CharField(blank=True, default='', max_length=20, null=True)),
            ],
        ),
    ]
