# Generated by Django 4.1.7 on 2025-01-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='page_name',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
