# Generated by Django 4.1.7 on 2025-01-24 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_userinfo_page_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default='2025-01-24 18:09:07.222578+00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='path',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='referer',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='session_id',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
