# Generated by Django 4.1.7 on 2025-01-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_userinfo_date_userinfo_path_userinfo_referer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='path',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='referer',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='session_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
