# Generated by Django 4.1.7 on 2023-12-06 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('username', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=254)),
                ('phone', models.CharField(default='', max_length=20)),
                ('email_verified', models.BooleanField(default=False)),
                ('user_status', models.CharField(default='Buyer', max_length=20)),
                ('addressline1', models.CharField(default='', max_length=100)),
                ('addressline2', models.CharField(default='', max_length=100)),
                ('addressline3', models.CharField(default='', max_length=100)),
                ('pin', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
                ('state', models.CharField(default='', max_length=100)),
                ('country', models.CharField(default='', max_length=100)),
                ('pic', models.ImageField(blank=True, default=None, null=True, upload_to='images/')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller', models.CharField(default='E-Shop', max_length=100)),
                ('name', models.CharField(default='', max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('discount', models.IntegerField(default=0)),
                ('promotion_price', models.IntegerField(default=0)),
                ('tags', models.CharField(default='', max_length=200)),
                ('size', models.CharField(default='', max_length=50)),
                ('popularity', models.IntegerField(default=0)),
                ('stock', models.CharField(default='', max_length=20)),
                ('description', models.TextField(default='')),
                ('sale', models.BooleanField(default=False)),
                ('pic1', models.ImageField(blank=True, default=None, null=True, upload_to='images/')),
                ('pic2', models.ImageField(blank=True, default=None, null=True, upload_to='images/')),
                ('pic3', models.ImageField(blank=True, default=None, null=True, upload_to='images/')),
                ('pic4', models.ImageField(blank=True, default=None, null=True, upload_to='images/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom.brand')),
                ('mainCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom.maincategory')),
                ('subCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('username', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('phone', models.CharField(default='', max_length=20)),
                ('email_verified', models.BooleanField(default=False)),
                ('user_status', models.CharField(default='', max_length=20)),
                ('addressline1', models.CharField(default='', max_length=100)),
                ('addressline2', models.CharField(default='', max_length=100)),
                ('addressline3', models.CharField(default='', max_length=100)),
                ('pin', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
                ('state', models.CharField(default='', max_length=100)),
                ('country', models.CharField(default='', max_length=100)),
                ('pic', models.ImageField(blank=True, default=None, null=True, upload_to='images/')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trackingnum', models.CharField(default='', max_length=100)),
                ('courier', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Shop_page_view_count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_view_count', models.IntegerField(default=0)),
                ('shop_view_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom.buyer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom.product')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller', models.CharField(default='E-Shop', max_length=20)),
                ('address', models.CharField(default='', max_length=500)),
                ('subtotal', models.IntegerField(blank=True, default=0, null=True)),
                ('shipping', models.IntegerField(blank=True, default=0, null=True)),
                ('ordertotal', models.IntegerField(blank=True, default=0, null=True)),
                ('paymentmethod', models.CharField(blank=True, default='COD', max_length=30, null=True)),
                ('paymentstatus', models.CharField(blank=True, default='Pending', max_length=20, null=True)),
                ('orderstatus', models.CharField(blank=True, default='Not Packed', max_length=20, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('rzppid', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('rzpoid', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('rzpsid', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom.buyer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q', models.IntegerField(default=1)),
                ('total', models.IntegerField(default=0)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom.payment')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom.product')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('productid', models.IntegerField(default=None)),
                ('price', models.IntegerField(default=0)),
                ('promotion_price', models.IntegerField(default=0)),
                ('image', models.URLField(default=None)),
                ('quantity', models.IntegerField(default=0)),
                ('subtotal', models.IntegerField(default=0)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom.buyer')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('phone', models.CharField(default='', max_length=20)),
                ('address1', models.CharField(default='', max_length=100)),
                ('address2', models.CharField(default='', max_length=100)),
                ('landmark', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
                ('state', models.CharField(default='', max_length=100)),
                ('country', models.CharField(default='', max_length=100)),
                ('pincode', models.CharField(default='', max_length=20)),
                ('addresstype', models.CharField(default='', max_length=20)),
                ('date', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom.buyer')),
            ],
        ),
    ]
