# Generated by Django 4.1.7 on 2023-12-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0002_buyer_product_shipment_shipmenttracking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='pic',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='shopprofile/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pic1',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='shopimages/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pic2',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='shopimages/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pic3',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='shopimages/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pic4',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='shopimages/'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='pic',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='shopprofile/'),
        ),
    ]
