# Generated by Django 4.1.7 on 2023-12-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0003_alter_buyer_pic_alter_product_pic1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colour',
            field=models.CharField(default='', max_length=50),
        ),
    ]
