# Generated by Django 4.1.7 on 2023-07-14 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='date',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
