# Generated by Django 4.1.7 on 2023-07-31 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='todo_description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
