# Generated by Django 4.1.7 on 2023-08-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_todo_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo_page_view_count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_home_view_count', models.IntegerField(default=0)),
            ],
        ),
    ]
