# Generated by Django 4.1.7 on 2023-05-08 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bloger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('pic', models.ImageField(blank=True, default=None, null=True, upload_to='blogprofile/')),
                ('bio', models.TextField(blank=True, default='', null=True)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreatePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default=True, null=True)),
                ('pic1', models.ImageField(blank=True, default=None, null=True, upload_to='blogimages/')),
                ('date', models.DateTimeField(auto_now=True)),
                ('bloger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.bloger')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('bloger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.bloger')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.createpost')),
            ],
        ),
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now=True)),
                ('follows', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.bloger')),
            ],
        ),
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.bloger')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Commented', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('bloger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.bloger')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.createpost')),
            ],
        ),
    ]
