# Generated by Django 4.1.7 on 2023-05-10 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follower',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.bloger'),
        ),
        migrations.AlterField(
            model_name='follower',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
