# Generated by Django 4.1.7 on 2023-07-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_follower_follower_alter_follower_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page_view_count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_view_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='createpost',
            name='post_view_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bloger',
            name='date',
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='createpost',
            name='date',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
