# Generated by Django 4.1.7 on 2023-07-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_page_view_count_delete_page_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloger',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='createpost',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
