from django.urls import path
from .views import *
from django.conf.urls.static import static
from allin1.settings import MEDIA_ROOT, MEDIA_URL


urlpatterns = [
    path('', home, name='home'),
    path('about/', about, name='about'),
    path('contact/', contact, name='contact'),
    #     path('shop/<str:mc>/<str:sc>/<str:br>/', shop, name='shop'),
    path('shop/<str:pk>/', shop, name='shop'),
    path('productInfo/<str:pk>/', productInfo, name='productInfo'),
    path('userprofile/addProduct/', addProduct, name='addProduct'),
    path('userprofile/editProduct/<str:pk>',
         editProduct, name='editProduct'),
    path('userprofile/delProduct/<str:pk>',
         delProduct, name='delProduct'),
    path('wishlist/', wishlist, name='wishlist'),
    path('wishlistAdd/<str:pk>/', wishlistAdd, name='wishlistAdd'),
    path('wishlistRemove/<str:pk>/', wishlistRemove, name='wishlistRemove'),
    path('cart/', cart, name='cart'),
    path('cartCreate/<str:pk>/', cartCreate, name='cartCreate'),
    path('cartUpdate/<str:pk>/<str:update>',
         cartUpdate, name='cartUpdate'),
    path('cartDelete/<str:pk>', cartDelete, name='cartDelete'),
    path('confirmOrder/', confirmOrder, name='confirmOrder'),
    path('payment/', payment, name='payment'),
    path('orders/', orders, name='orders'),
    path('orderDetails/<str:pk>', orderDetails, name='orderDetails'),
    path('orderEdit/<str:pk>', orderEdit, name='orderEdit'),
    path('ordersTracking/<str:pk>', ordersTracking, name='ordersTracking'),
    path('orderCancel/<str:pk>', orderCancel, name='orderCancel'),
    path('address/', userAddress, name='userAddress'),
    path('addAddress/', addAddress, name='addAddress'),
    path('editAddress/<str:pk>', editAddress, name='editAddress'),
    path('delAddress/<str:pk>', delAddress, name='delAddress'),
    path('signintemplate/', signintemplate, name='signintemplate'),
    path('signin/', signin, name='signin'),
    path('guest/<str:pk>/', guest, name='guest'),
    path('signup/<str:pk>/', signup, name='signup'),
    path('forgetPassword/', forgetPassword, name='forgetPassword'),
    path('forgetPassword/verify-OTP/',
         forgetPasswordOTP, name='forgetPasswordOTP'),
    path('forgetPassword/resetPassword/',
         forgetPasswordReset, name='forgetPasswordReset'),
    path('admin/', adminPage, name='adminPage'),
    path('userprofile/', userProfile, name='userprofile'),
    path('editprofile/<int:pk>', editProfile, name='editprofile'),
    path('email-verify-OTP/', emailVerifyOTP, name='emailVerifyOTP'),
    path('logout/', ecomlogout, name='ecomlogout'),
] + static(MEDIA_URL, document_root=MEDIA_ROOT)
